name: Setup
description: Common setup for iOS CI

runs:
  using: composite
  steps:
    - name: Mise (Ruby + Tuist + SwiftLint)
      uses: jdx/mise-action@v3

    - name: Cache gems
      uses: actions/cache@v4
      with:
        path: vendor/cache
        key: ${{ runner.os }}-mise-gems-${{ hashFiles('Gemfile.lock') }}

    - name: Install Fastlane with cache
      shell: bash
      run: bundle cache

    - name: Set Xcode 26.3
      shell: bash
      run: sudo xcode-select -s /Applications/Xcode_26.3.app

    - name: Cache Tuist .build
      uses: actions/cache@v4
      with:
        path: Tuist/.build
        key: tuist-cache-${{ hashFiles('Tuist/Package.resolved') }}
        restore-keys: |
          tuist-cache-
