name: Push

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  cache_warmup_and_tests:
    name: Cache warmup & tests 
    runs-on: macos-26
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Common setup
        uses: ./.github/actions/setup

      - name: Run cache warmup and tests
        run: |
          bundle exec fastlane ci_push
        env:
          CONNECT_API_KEY: ${{ secrets.CONNECT_API_KEY }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_TEAM_ID: ${{ secrets.FASTLANE_TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          TUIST_TOKEN: ${{ secrets.TUIST_CONFIG_TOKEN }}
          SENTRY_DSYM_TOKEN: ${{ secrets.SENTRY_DSYM_TOKEN }}
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
